port = 8081
port = ${?INVENTORY_SERVICE_PORT}

metrics-port = 9091
metrics-port = ${?INVENTORY_SERVICE_METRICS_PORT}

service-name = "inventory-service"
service-name = ${?INVENTORY_SERVICE_NAME}

induced-failure {
  failure-rate = 0.0
  failure-rate = ${?INVENTORY_INDUCED_FAILURE_RATE}
  delay = 0ms
  delay = ${?INVENTORY_INDUCED_DELAY_MS}
}
