port = 8080
port = ${?ORDER_SERVICE_PORT}

metrics-port = 9090
metrics-port = ${?ORDER_SERVICE_METRICS_PORT}

inventory-service-base-url = "http://localhost:8081"
inventory-service-base-url = ${?INVENTORY_SERVICE_BASE_URL}

postgres {
  host = "localhost"
  host = ${?POSTGRES_HOST}
  port = 5432
  port = ${?POSTGRES_PORT}
  database = "orders"
  database = ${?POSTGRES_DB}
  user = "orders"
  user = ${?POSTGRES_USER}
  password = "orders"
  password = ${?POSTGRES_PASSWORD}
}

resilience {
  retry {
    max-retries = 3
    max-retries = ${?ORDER_SERVICE_RESILIENCE_MAX_RETRIES}
    base-delay = 100ms
    base-delay = ${?ORDER_SERVICE_RESILIENCE_BASE_DELAY}
  }
  circuit-breaker {
    failure-threshold = 5
    failure-threshold = ${?ORDER_SERVICE_RESILIENCE_FAILURE_THRESHOLD}
    reset-timeout = 30s
    reset-timeout = ${?ORDER_SERVICE_RESILIENCE_RESET_TIMEOUT}
  }
}
